plugin: amazon.aws.aws_ec2
regions:
  - eu-west-2

filters:
  tag:Project: offerzen-aws-assessment
  tag:Environment: dev
  instance-state-name: running

hostnames:
  - private-ip-address

compose:
  ansible_user: "'ec2-user'"

groups:
  ui: "'ui-instance' in (tags.Name | default(''))"
  backend: "'backend-instance' in (tags.Name | default(''))"
